services:
    command.oauth_create_client:
        class: AppBundle\Command\OAuthCreateClientCommand
        arguments:
            - @fos_oauth_server.client_manager.default
        tags:
            -  { name: console.command }
